language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - ATOMIST_REPO_USER=travis-mvn-deploy
  - secure: l7jUJMW3tygH5VF4f7L2e2/av5O35MuvRldF1LP/DTagMwRQ9TQ0MYImm3ymJBJGG43Cq5hByMB34IgO5JWl0G9/xEyfi7kQVmOQiqU6EkSOTEHNqevERmTxXLeNzgAYkPEPCL1YTAUWDBw70AM1p82dybVppCtMslRm5RzZvpfzajbM+AlkiBiIfUngb+0UVYSogHJOgwJbfzRxLio00Yq5IxWiEDxPTC8D9sL7aSE+PPH/oOqTlBSliTFS+69LGVhdB0oud9YXXGWagRJBAnoYqgNL+rSq5PRg3vsvQSBlziPvjWFrGKiKtYC4FZB4bcdoX9OJVwtHtHq34E7aK+BUF1UhGW1NucThNf3RbUHh2Cgjv7U9smuu1TZGs5hi86rNKy/64QuSo1QFMTdu16zNh3CxgfPi8Jt1upJo9v4z0CpW8yWc5Mnm830BYG3gBwP9NKvjeywEgpGoJoXdpMhZweCEvE/Tab4Lhr3qU0DWub3PuLFJOEmE8JlmSGGFkRClUMlNjQuExlyx0LK2tRqlwA7Lx7y5dFY8XLmxid18KMNn/7jeLbV1p5m/4a8RxgbH44UvtZlPpfjzUio3/WmeynwpCt+fONJ1PJudTz7kQl92BdwQ8Qy0MHa74YXadCKSIBGLjQrMxIRH3hGcdNuoTjt7l9QIbBFUDEgxyWE=
  - secure: b7hMTnWP5x4a75Dycw465ohFodkFIJGd0PDeD9J8szNV9l4N1bjdiqb/k1PY1abuBcjk1NDtd24N6mpEFTvSzTP4EnWHhKLvCr4pqWewwdjzp0uQkE2UtPCSvdmOYnVHwrvIT0MzhL+dq90RmUpFkPZS6GAywKWcs6GwMNvLk0T4Awf9nqyiq8pxgBeu4xvviy+hOWy11eqviXLaxrqdvJXJPTQkkipBUXbGzVPiK3N/3IpOEdCLxKOpp59rN3mHSyXJG+SUe4IboV7NTNxWwjsukG9CbtRv59WAUhkNjsckTg0g1mVPu6uJtek3d5q/k3ZyC0Gu+FwE0+ESVWvBRXxIbZCGUVInmWSJiZ8+kAkCQYWo+LE8zF9/zInjiazBrWQjzBH+AjGw/BBwW9rY0GrLevU19wGxtJGjdXXBGhp4B8KJVYcnkqDonTruc6GxnAZ96+0C79w52HSQo+ikLDxrzNHD4ONkwHqd+OyqgiEEzT4ASnDGAGGRU7cjtDz0IN/q0kP/GlquhTERuwQZ/mbl3WtNhTdi9TaSt2x4qUOAbOO6V2afPfsTA1oWiA4N2EoU0m8MwRLgJr3QYuxPojohPfWVmrIOFHbkaJlbx64WwPk+EFA96hod//aFox9RabQ2fIp1oUltTo8fvVUbwt4hyEEiTba6Lm1qw+0nBwQ=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: P+g6EWJcz6ARFKMqYBMYfvk02UBCSpsvskjBIGG33mbu9Lp0Kp2kgg7yIrRB0yO9B9VpxfLaKOVuSdJuUdvmbcRxIF/zZ/UsJWEkABXKC2PazzaV0X5QRkJX5bytbrwUgl/DraBnE0eJVVVWltOG75Cm19fvFpVXcIAbgJlgc2Z8YrFcIS8L4OYi916qpKMpoVIIsGbSUjd7liMvasWWCbbDit+msiCUCMAOsEe7OzTfOi57KSnu4p4lni10FtMjTIzBwfX4H3ntEkQ767aWvkkl1KYt8MTziPPOkXT3wNjlsrDJU1X3C4ZRtZ8E7tPL/t1nVxPIRmvUPgbWxu93bHLcG/H6jaTF6AhtdFqFJ9Dw47VHALR0yZP4gMminewLA/HOQECC+ejN/OtF/ebsFZHFVj+Ya0l/tfDOoZ/Yr0BxyPqf5m1aS6D3QbL4WSTS4iL0PZKFOrEHI7PhwoVSE6JUN6EF73W1heQBABjZ0rfDxrln0fy3Fm56e2foqB9PmCgkV4dv2WC/TqgCTHIYDFHP4/HBsrg73dXMGmmo4dnj8knKdr0KyDljWQHqwP2Mhq108RVpcFGD7HFnajRS1/n8SHoRDI7xYEehxo9letkQKo2ScbaUWKf/MBDt5Wf1uOBu+ucYj3jH3nxZHsW2OjfKLVudxniBsfkB42XOG+c=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
