language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: V7kStDwimEFt34/Yu2X7x2MNxleGJRKHQlRohSgdKnTb4ybd1MHRss1gJk7zeZHLPiEyTFPteNFfgpjQicQfrTPja4ilLkrwu++lIwHD0BcveKZ9sHoOBF7fqB7IsDzZf8t3c5h75lKw/Vz1zN9QlHZRNqfyiUfEZfsgHS+2M5E/rFT2VtQX3pI2CYw4gWdbFW+BpUmrWBr/PhM5kmcuB/mmA9672RzK9HQGVMqnfus5DKGnuum4gAIaCZ7IiSVO2NusnoK7KTCLGqBPBBfmPBr/we218urNaJe+brt3xudux9ge5JMQ8TP1qLuRAN2PNQVFC+HOD1BIpK9JsFe5U+r+AVbLeJo8SfLsE+o3iw2fm2nSa6JILUXFyUdz7BXUB4a+T/6bQ9z8ucxwcFx607zv5e7aIAf5qgGL/f4USPGecXOXirrGBaj6Zk6dLziXkTi4gbgsFwYnJVoNYVZ8LSb83D2FcgPNWoBfgD8UXdsCDfOoOG4ch6I6bLzXiI7eAmSROO1bDw1iij7dgFieLtM61PAwlrQYQUHAoQ1y6Qarvranv85dNgCK75jNtS1ZJS/XnK5C3j8WpgD2HhzJkq6TuuOKenXIvSIBsZDAAYke/DYH46ivoy1t2rpzO7+U9i8BJJMAf/TAHOhOZ3jjGSY8K35d/s/2fpfKs226azI=
  - secure: nlbGAYiMgWNVVpxVxhyK8IZkHpsMokrol3gFwBUD8m9RnsF38oPJ1r+f47mhKu6g3DuVVBZ6qbnG+x5HyHmVvD3dW7/zxNoeJZ2BeJUBAA1QuOwpoNGn3U30wlz3b0F+wKvAd1uKVt1e86Aplm9DJyiS3D2jPqV2bqT3Eo7wEt/i5pLaUVoLNfwvke7j8qibTYsQ7fJ7Vuj59lasqDSUhWV4MNBf2l59RYaaqRBNN1u0FX5Tr987JrFE7wwZK1IFTfamteaWIJt/cIlHSKzx+PwVU8ckif1S5jqOKQQldLryzU8Z50uErakhrkSCQ0JfX+8iF8vfgflwY/StqI2qAV4ltjAVza1KoUXXji7k7/zHYcT1GXXgddKOTtndN6HGQOGyRpHaTcFXlVu0xPTCLchHR+DTEktjleFXRiJ8r6KGUCePAxGbN1/OjO8Jiegb/n4tADFpfHnAp7COvSEdZtsy8S2FleFG7up0k+kzMj8l0+C15bgowmvjhM9dGI0frRbbsYLYb31LtBLky2+u6XbO8t5wLGyzGQBSvsNKpTXB21DeRqyIopKrvY/8BLUFip1YBZ36TteN7Ykrcz0cHVRpIVQzpM/4Fxjj8mvgGPx40lQoIDKLROqUGk++5o2PEerwUhFnK5uWe26pM88JJigqzb1kHlfHm+dZo3ImZVk=
  - secure: ncX/uIJXfIMPYaXNxa4f+zXVA1yv4QaiRhcRmuwWYIaFiFA3syilOKd8mbgv2aR2jFBNgiaRtMVF2KrCLeiY1rUWYo58ECQBSTKQjbxrMVoSmh8ozP4jdJLDDc+j6sev01Hx9tgUOLbyJxSmEXBPZIaO1Aq5u+NvH/ZJagxoNzawvqMccyjUjJ9QQDuYygFVhJRhF0DEvjRoBYxVWJaseDZELwnDuFoE3/0RUpMrMrQi1XfGoIldzsp8B7RQ5QpoPA6GZUWyTygyTxLxEgF7p9VxDlRBC+7F6rnobWKxI9be3hXTrjsKkxUNLTnBtnnRCVX/1SL7TM5AT7PzxMHs6w7IoR9sRWUeOogJz/TKp/MP6IgENi0MNqr0C6NKvIPpVrAvQtquUfzfPnjVQgkPoRrVSv4OEoIMM9VF3hjblZEUVf+42WOzVdZYflu7rQyGDbZVOpN0Mx7uJUMMtGt8hJfVTTBS+qqXxQTAIoOJTugzClzkfhCEbK7cWjYHb3a1L+WVKUFFHmLjDOuMbzFIKVroQNOXtcZQR6Q92ZPIz/OmohKEn6+FSHLu61onUm/JBv8UphWuTQBcUOpD5zXHdhqe6W0fZdPCNSizYNTIhSmb0YWkYtnyOIPflJ+3WKLwQqtJEC8lHycJgGAHy7xhLJo6ZCE1KRKsa8E6f+UDies=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: P+g6EWJcz6ARFKMqYBMYfvk02UBCSpsvskjBIGG33mbu9Lp0Kp2kgg7yIrRB0yO9B9VpxfLaKOVuSdJuUdvmbcRxIF/zZ/UsJWEkABXKC2PazzaV0X5QRkJX5bytbrwUgl/DraBnE0eJVVVWltOG75Cm19fvFpVXcIAbgJlgc2Z8YrFcIS8L4OYi916qpKMpoVIIsGbSUjd7liMvasWWCbbDit+msiCUCMAOsEe7OzTfOi57KSnu4p4lni10FtMjTIzBwfX4H3ntEkQ767aWvkkl1KYt8MTziPPOkXT3wNjlsrDJU1X3C4ZRtZ8E7tPL/t1nVxPIRmvUPgbWxu93bHLcG/H6jaTF6AhtdFqFJ9Dw47VHALR0yZP4gMminewLA/HOQECC+ejN/OtF/ebsFZHFVj+Ya0l/tfDOoZ/Yr0BxyPqf5m1aS6D3QbL4WSTS4iL0PZKFOrEHI7PhwoVSE6JUN6EF73W1heQBABjZ0rfDxrln0fy3Fm56e2foqB9PmCgkV4dv2WC/TqgCTHIYDFHP4/HBsrg73dXMGmmo4dnj8knKdr0KyDljWQHqwP2Mhq108RVpcFGD7HFnajRS1/n8SHoRDI7xYEehxo9letkQKo2ScbaUWKf/MBDt5Wf1uOBu+ucYj3jH3nxZHsW2OjfKLVudxniBsfkB42XOG+c=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
